name: Publish PowerShell Module
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Standard 2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.x'
    - name: Restore dependencies
      run: dotnet restore acumatica-customizationProjectTools.sln
    - name: Build module in Release mode
      run: dotnet build acumatica-customizationProjectTools.sln -c Release
    - name: Test Module before Publish
      run: Test-ModuleManifest -Path .\AcuPackageTools\AcuPackageTools.psd1
    - name: Publish to PowerShell Gallery
      run: Publish-Module -Path AcuPackageTools.psd1 -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }}