name: Publish PowerShell Module
on:
    push:
        tags:
          - '[0-9]*.[0-9]*.[0-9]*'
          - 'v[0-9]*.[0-9]*.[0-9]*'
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore acumatica-customizationProjectTools.slnx

    - name: Build module in Release mode
      run: dotnet build acumatica-customizationProjectTools.slnx -c Release

    - name: Update Module Version from Tag
      shell: pwsh
      run: |
        $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
        $commitMsg = git log -1 --pretty=%B
        $releaseNotes = ($commitMsg -join "`n").Trim()
        Write-Host "GitHub Tag: $tag"
        Write-Host "Release Notes: $releaseNotes"
        .\.github\Update-ModuleVersion.ps1 -GitHubTag $tag -ReleaseNotes $releaseNotes

    - name: Test Module Manifest before Publish
      shell: pwsh
      run: Test-ModuleManifest -Path .\AcuPackageTools\AcuPackageTools.psd1

    - name: Publish to PowerShell Gallery
      shell: pwsh
      env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
      run: |
          Publish-Module -Path .\AcuPackageTools -NuGetApiKey $env:NUGET_API_KEY -Verbose
