name: Publish PowerShell Module
on:
    push:
        tags:
          - '[0-9]*.[0-9]*.[0-9]*'
          - 'v[0-9]*.[0-9]*.[0-9]*'
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore acumatica-customizationProjectTools.slnx

    - name: Build module in Release mode
      run: dotnet build acumatica-customizationProjectTools.slnx -c Release

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run Unit Tests
      shell: pwsh
      run: |
        $testResults = Invoke-Pester -Path .\tests -ExcludeTag Integration -PassThru -OutputFormat NUnitXml -OutputFile TestResults.xml
        if ($testResults.FailedCount -gt 0) {
          Write-Error "Failed $($testResults.FailedCount) tests"
          exit 1
        }

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xml

    - name: Update Module Version from Tag
      shell: pwsh
      run: |
        $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
        $commitMsg = git log -1 --pretty=%B
        $releaseNotes = ($commitMsg -join "`n").Trim()
        Write-Host "GitHub Tag: $tag"
        Write-Host "Release Notes: $releaseNotes"
        .\.github\Update-ModuleVersion.ps1 -GitHubTag $tag -ReleaseNotes $releaseNotes

    - name: Test Module Manifest before Publish
      shell: pwsh
      run: Test-ModuleManifest -Path .\AcuPackageTools\AcuPackageTools.psd1

    - name: Publish to PowerShell Gallery
      shell: pwsh
      env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
      run: |
          Publish-Module -Path .\AcuPackageTools -NuGetApiKey $env:NUGET_API_KEY -Verbose
