name: Publish PowerShell Module
on:
    push:
        tags:
          - '*'
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore acumatica-customizationProjectTools.sln

    - name: Build module in Release mode
      run: dotnet build acumatica-customizationProjectTools.sln -c Release

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Test Api Cmdlets
      run: Invoke-Pester -Path .\AcuPackageTools.Tests\Invoke-ApiPackage.Test.ps1

    - name: Test Service Cmdlets
      run: Invoke-Pester -Path .\AcuPackageTools.Tests\Invoke-ServicePackage.Test.ps1

    - name: Test PackageBuild Cmdlets
      run: Invoke-Pester -Path .\AcuPackageTools.Tests\Invoke-PackageBuild.Test.ps1

    - name: Test Module Manifest before Publish
      run: Test-ModuleManifest -Path .\AcuPackageTools\AcuPackageTools.psd1

    - name: Publish to PowerShell Gallery
      env:
          NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
      run: |
          $version = $env:GITHUB_REF.Replace("refs/tags/", "")
          Publish-Module -Path .\AcuPackageTools -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -Verbose -Version $version
