name: Test PowerShell Module
on:
    push:
        branches: ['*']
    pull_request:
        branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore acumatica-customizationProjectTools.slnx

    - name: Build module in Release mode
      run: dotnet build acumatica-customizationProjectTools.slnx -c Release

    - name: Test Module Manifest
      shell: pwsh
      run: Test-ModuleManifest -Path .\AcuPackageTools\AcuPackageTools.psd1

    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Run Unit Tests
      shell: pwsh
      run: |
        $testResults = Invoke-Pester -Path .\tests -ExcludeTag Integration -PassThru -OutputFormat NUnitXml -OutputFile TestResults.xml
        if ($testResults.FailedCount -gt 0) {
          Write-Error "Failed $($testResults.FailedCount) tests"
          exit 1
        }

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xml
